### ISSUE TITLE
using TCRβ only instead of 'TCRα+β pair' ?

### ISSUE THREAD

**Issue by Ruismart** [jcao89757/TESSA#1]
Hi, I'm fresh in sc-TCR related analysis, glad to see this new tool.    
As I know, to decide a clonotype of one T cell, one ’TCRα + TCRβ pair‘ profile should be necessarily provided. But some sc-TCR analysis based on 10x genomics vdj technology which has much lower rate to detect TCRα have to use TCRβ only.  I'm not sure about how many false-positives it may bring in. e.g. x50 copies of one TCRβ type are detected in two different tissues, could say these two tissues both have this kind of T cell, but if add TCRα result, might find that no 'α+β pair' are overlapped between them.  
My question is that: have you thought about this issue, and would 'using TCRβ only' affect tessa method like correlation of TCR type x  Tcell expression or sth. else ?

**Comment by jcao89757** [comment]
Hi Shaorui,

Thanks for your interest in our tool! 

That's a great question! Acturally our paper (https://www.nature.com/articles/s41592-020-01020-3) discussed about the possible future direction to incorporate the CDR3α sequences and V/J genes into the modeling process. Please check the third paragraph of Discussion and the 'Embedding TCR sequences' section of Methods. It is true that incorporating TCRα chains will increace the accuracy of the model, however, it will also greatly decrease the sample sizes with current technologies. 

Please also refer to this post (https://www.researchgate.net/post/For_T-Cell_Receptors_why_is_there_more_focus_on_the_beta_than_alpha_chain) as it answers your question about different TCRα-β chain pairs with the same TCRβ chains. Basically, this could happen theoretically (we did not observe many such cases in our dataset though), however, since TCRβ chains are responsible for most of the TCR fucntions, we consider those pairs with only the same TCRβ chains as being specific to the same or similar antigens. 

Thanks again for postiing your thoughts! Hope this information may be helpful. Please let me know if you have any other questions!

Best regards, Ze

**Comment by Ruismart** [comment]
Hi Ze, 

That helps quite a lot, thanks.
