### ISSUE TITLE
what does node size represent in the figure generated from plot_Tessa_clusters?

### ISSUE THREAD

**Issue by gancao** [jcao89757/TESSA#8]
what does node size represent in the figure generated from plot_Tessa_clusters? How to understand the figure?

**Comment by jcao89757** [comment]
Hi @gancao，

Thanks for your careful observation!

I was assuming that you mentioned 'node' as the 'node_size' variable in the code. The 'nodes' here means the vertices in our graph, which represent TCR clones in our function. The size of each point represents the clonal size of one TCR clone. TCR clones within one network are plotted in one color, and linked with segments start from the central TCR to the peripheral TCRs. The locations of TCRs on the graph are randomly generated. The information we want to achieve from this plot is a global observation of the numbers of TCRs within networks and the clonal sizes of TCRs. 

Please let me know if you have further questions. Thanks again for your interest!

Best regards, Ze

**Comment by gancao** [comment]
Thanks for your patience! I am still confused, because I didn't use the clonetype_id and frequency as input information, just CDR3 sequence and barcode. What did the clonal size mean you mentioned? In the following picture I obtained from my data using TESSA, the node sizes of some networks looked very different, why? Could you please tell me more detailed information? Does one node represent a TCR?


| |
甘草
|
|
18883990694@163.com
|
签名由网易邮箱大师定制
On 2/26/2021 00:19，Ze Zhang<notifications@github.com> wrote：

Hi @gancao，

Thanks for your careful observation!

I was assuming that you mentioned 'node' as the 'node_size' variable in the code. The 'nodes' here means the vertices in our graph, which represent TCR clones in our function. The size of each point represents the clonal size of one TCR clone. TCR clones within one network are plotted in one color, and linked with segments start from the central TCR to the peripheral TCRs. The locations of TCRs on the graph are randomly generated. The information we want to achieve from this plot is a global observation of the numbers of TCRs within networks and the clonal sizes of TCRs.

Please let me know if you have further questions. Thanks again for your interest!

Best regards, Ze

**Comment by jcao89757** [comment]
Hi @gancao ,

The figure is missing at my side, but I seem to understand your questions. Pleasse correct me if I'm wrong.

One node acturally represent one unique TCR beta-chain CDR3 sequence in your input data, and the clonal size of each node represents the number of cells that the corresponsing CDR3 sequence was detected. The clonotypes are defined by the CDR3 sequences, therefore tessa does not require 'clonotype_ids' as its input. We use TCR beta-chain CDR3 sequences to identify TCR clonotypes because those are the most related regions to T cell functions. Please find more details in the discussion section of our paper (https://www.nature.com/articles/s41592-020-01020-3). 

For your second question, tessa networks are built depending on the TCR specificity, rather than their clonal sizes. TCRs within the same network are assumed to target the same antigen, and their clonal sizes do not influence their targeting specificity. Therefore it's OK to have TCRs with different clonal sizes in one network.

Please let me know if there are other things unclear for you. I would be happy to explain! Thanks again for all your questions.

Best regards, Ze

**Comment by gancao** [comment]
Thanks, I understood it!  
The center cdr3 is the center node of each network? If it is right, what's interesting is that the center cdr3 in each network is less the cdr3 sequence with the largest clonal size, It means the cdr3 with the largest clonal size is usually non-center cdr3 in each network in my data. As the paper mentioned, the center tcr have better avidity toward the antigen. Generally, The tcr will clonally expand if exposed the target antigen. I think this is a keyponit.
Good luck!
| |
甘草
|
|
18883990694@163.com
|
签名由网易邮箱大师定制
On 2/26/2021 09:52，甘草<18883990694@163.com> wrote：
Thanks for your patience! I am still confused, because I didn't use the clonetype_id and frequency as input information, just CDR3 sequence and barcode. What did the clonal size mean you mentioned? In the following picture I obtained from my data using TESSA, the node sizes of some networks looked very different, why? Could you please tell me more detailed information? Does one node represent a TCR?


| |
甘草
|
|
18883990694@163.com
|
签名由网易邮箱大师定制
On 2/26/2021 00:19，Ze Zhang<notifications@github.com> wrote：

Hi @gancao，

Thanks for your careful observation!

I was assuming that you mentioned 'node' as the 'node_size' variable in the code. The 'nodes' here means the vertices in our graph, which represent TCR clones in our function. The size of each point represents the clonal size of one TCR clone. TCR clones within one network are plotted in one color, and linked with segments start from the central TCR to the peripheral TCRs. The locations of TCRs on the graph are randomly generated. The information we want to achieve from this plot is a global observation of the numbers of TCRs within networks and the clonal sizes of TCRs.

Please let me know if you have further questions. Thanks again for your interest!

Best regards, Ze

**Comment by jcao89757** [comment]
Hi @gancao,

Glad to know that you find my comments helpful!

It seems that we have different understandings of the analysis you mentioned in your last comment. Please let me explain and we can discuss the ways to extract more information from your results. 

Please find detailed methods from the legend of Fig.2 in our paper. Briefly, we calculated the median of the clonal sizes of the non-center clones and compared the medians with the clone sizes of the center clones, rather than comparing all non-center clones with the center clones, and we observed more TCR networks with size(center clone)>median(size(non-center clones)) than the reverse. The most expanded TCR is not always the center TCR, but probablistically and overall, the center TCRs tend to have larger clone sizes than non-center ones.

Please feel free to let me know if you are not clear about this analysis or any other ones that exist in our paper! Again, I will be happy to share my experience.

Thanks for the dicussion!

Best regards, Ze
